### ISSUE TITLE
Calculate the FUV from the PUM and PUV

### ISSUE THREAD

**Issue by felixkollin** [DD2480-Group-11/assignment-1#103]
FUV[i] should be set to true if PUV[i] is false (indicating that the associated LIC should not hold back launch) or if all elements in PUM row i are true.

**Comment by AndreasHeiskanen** [comment]
I'm on it!

**Comment by felixkollin** [comment]
You can look at my PUM tests on how to test FUV, you can simply create the a pum and puv without needing to create everything else

**Comment by AndreasHeiskanen** [comment]
Thanks for the tip!

**Comment by AndreasHeiskanen** [comment]
Submitted PR with feature resolving this issue, assigned you @felixkollin as a reviewer.
